blogTitle = "Khanh Quoc Press"
mastHead = "QUOCKHANH"
authorName = "Quoc Khanh"
shortName = "khanhbq"
linkPrefix = ""
domain = "https://khanhquoc.press"
email = "khanhbq@innoteq.vn"
description = "By Quoc Khanh â€” a believer, dreamer and maker of things."
